[package]
name = "bottlerocket-agents"
version = "0.0.13"
edition = "2018"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
agent-common = { version = "0.0.13", path = "../../agent/agent-common" }
agent-utils = { version = "0.0.13", path = "../../agent/utils" }
bottlerocket-types = { version = "0.0.13", path = "../types" }
async-trait = "0.1"
aws-types = "0.54"
aws-sdk-ec2 = "0.24"
aws-sdk-ecs = "0.24"
aws-sdk-eks = "0.24"
aws-sdk-iam = "0.24"
aws-sdk-ssm = "0.24"
aws-sdk-sts = "0.24"
aws-sdk-cloudformation = "0.24"
base64 = "0.20"
flate2 = "1.0"
hex ="0.4"
k8s-openapi = { version = "0.21.1", default-features = false, features = ["v1_24"] }
kube = { version = "0.89", default-features = false, features = ["config", "derive", "client"] }
log = "0.4"
maplit = "1"
openssh = { version = "0.9", features = ["native-mux"] }
testsys-model = { version = "0.0.13", path = "../../model" }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "blocking"] }
resource-agent = { version = "0.0.13", path = "../../agent/resource-agent" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.8"
sha2 = "0.10"
snafu = "0.7"
tar = "0.4"
test-agent = { version = "0.0.13", path = "../../agent/test-agent" }
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread", "time"] }
toml = "0.5"
tough = { version = "0.13", features = ["http"] }
url = "2"
uuid = { version = "1", default-features = false, features = ["serde", "v4"] }
