[package]
name = "controller"
version = "0.0.13"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
aws-config = "0.54"
aws-types = "0.54"
aws-sdk-cloudwatchlogs = "0.24"
env_logger = "0.10"
futures = "0.3"
http = "0"
k8s-openapi = { version = "0.21.1", default-features = false, features = ["v1_24"] }
kube = { version = "0.89", default-features = false, features = ["derive", "client", "rustls-tls"] }
kube-runtime = "0.89"
lazy_static = "1"
log = "0.4"
testsys-model = { version = "0.0.13", path = "../model" }
snafu = "0.7"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
