name: Build
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'tools/**'
      - '.github/dependabot.yml'
      - 'bottlerocket/tests/workload/**'
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'tools/**'
      - '.github/dependabot.yml'
      - 'bottlerocket/tests/workload/**'
    branches: [develop]
jobs:
  build:
    runs-on:
      group: bottlerocket
      labels: bottlerocket_ubuntu-latest_8-core
    steps:
      - uses: actions/checkout@v3
      - run: rustup default 1.78 && rustup component add rustfmt && rustup component add clippy
      - run: make build
        # If we forget to add yamlgen changes to our commits, this will fail.
      - name: ensure that git is clean
        run: test -z "$(git status --untracked-files=all --porcelain)"
      - run: make controller
      - run: make duplicator-resource-agent
      - run: make example-resource-agent
      - run: make example-test-agent
      - run: make example-test-agent-cli
      - run: make integ-test
        env:
          TESTSYS_SELFTEST_SKIP_IMAGE_BUILDS: true
          TESTSYS_SELFTEST_THREADS: 1
  images:
    runs-on:
      group: bottlerocket
      labels: bottlerocket_ubuntu-latest_16-core
    steps:
      - uses: actions/checkout@v3
      - run: make images
  license-check:
    # A small machine is OK for this independent job.
    runs-on: ubuntu-latest
    # If we already checked the PR, we don't need to check the actual push
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup default 1.78
      - run: make cargo-deny
